using System.Collections.Generic;

namespace amongus3902.Data
{
    public enum ZeldaSpriteSheet
    {
        LinkGreen,
        LinkBlue,
        LinkPurple,
        LinkRed,
        LinkPink,
        WhiteLink,
        Blocks,
        Gel,
        Goriya,
        Keese,
        Stalfos,
        Trap,
        WallMaster,
        Aquamentus,
        OldMan,
        Fireball,
        Compass,
        Map,
        Key,
        HeartContainer,
        TriforcePiece,
        WoodenBoomerang,
        Bow,
        Heart,
        Rupee,
        Arrow,
        Bomb,
        Fairy,
        Clock,
        WoodenSword,
        WoodenSwordDU,
        WoodenSwordRL,
        SwordBeam,
        WoodenArrow,
        ArrowDU,
        ArrowRL,
        MagicArrow,
        MagicArrowDU,
        MagicArrowRL,
        BombSmoke,
        MagicBoomerang,
        Fire,
        SwordBeamExplosion,
        DeathSparkle,
        Clink,
        RoomBorder,
        NorthDoor,
        WestDoor,
        EastDoor,
        SouthDoor,
        OldManText,
        GameOverText,
        GameWinText,
        TopDisplay,
        LevelOneMap,
        EmptyRoom,
        NoMap,
        FullHeart,
        HalfHeart,
        EmptyHeart,
        NoHeart,
        XCount,
        ZeroCount,
        OneCount,
        TwoCount,
        ThreeCount,
        FourCount,
        FiveCount,
        SixCount,
        SevenCount,
        EightCount,
        NineCount,
        ActiveWoodenSword,
        ActiveWoodenArrow,
        ActiveMagicArrow,
        ActiveWoodenBoomerang,
        ActiveMagicBoomerang,
        ActiveBomb,
        ActiveCandle,
        ActiveNoItem,
        HighlightWithMap,
        HighlightNoMap,
        PortalGun,
        OrangeProjectile,
        BlueProjectile,
        OrangePortal, 
        BluePortal,
        PauseScreen,
        PauseMapPieces,
        ItemSelect,
        RetirementText,
        Sus,
        Candle,
        SusSmoke, 
        ActivePortalGun
    }

    internal static class SpriteData
    {
        public readonly static List<(
            ZeldaSpriteSheet sheet,
            string fileName,
            int rows,
            int cols
        )> SheetDetailsRaw =
            new()
            {
                (ZeldaSpriteSheet.LinkGreen, "Sprites/linkp1", 10, 4),
                (ZeldaSpriteSheet.LinkBlue, "Sprites/linkp2", 10, 4),
                (ZeldaSpriteSheet.LinkPurple, "Sprites/linkp3", 10, 4),
                (ZeldaSpriteSheet.LinkRed, "Sprites/linkp4", 10, 4),
                (ZeldaSpriteSheet.LinkPink, "Sprites/linkp5", 10, 4),
                (ZeldaSpriteSheet.WhiteLink, "Sprites/whitelink", 1, 1),
                (ZeldaSpriteSheet.Blocks, "Sprites/Environment/blocks", 3, 4),
                //
                (ZeldaSpriteSheet.Gel, "Sprites/Enemies/gel", 1, 2),
                (ZeldaSpriteSheet.Goriya, "Sprites/Enemies/goriya", 4, 2),
                (ZeldaSpriteSheet.Keese, "Sprites/Enemies/keese", 1, 2),
                (ZeldaSpriteSheet.Stalfos, "Sprites/Enemies/stalfos", 1, 2),
                (ZeldaSpriteSheet.Trap, "Sprites/Enemies/trap", 1, 1),
                (ZeldaSpriteSheet.WallMaster, "Sprites/Enemies/wallmaster", 1, 4),
                (ZeldaSpriteSheet.Aquamentus, "Sprites/Enemies/aquamentus", 2, 2),
                //
                (ZeldaSpriteSheet.OldMan, "Sprites/Environment/oldman", 1, 1),
                (ZeldaSpriteSheet.Fire, "Sprites/Environment/fire", 1, 2),
                //
                (ZeldaSpriteSheet.Compass, "Sprites/Items/compass", 1, 1),
                (ZeldaSpriteSheet.Map, "Sprites/Items/map", 1, 1),
                (ZeldaSpriteSheet.Key, "Sprites/Items/key", 1, 1),
                (ZeldaSpriteSheet.HeartContainer, "Sprites/Items/heartcontainer", 1, 1),
                (ZeldaSpriteSheet.TriforcePiece, "Sprites/Items/triforcepiece", 1, 2),
                (ZeldaSpriteSheet.WoodenBoomerang, "Sprites/Items/boomerang", 3, 3),
                (ZeldaSpriteSheet.Bow, "Sprites/Items/bow", 1, 1),
                (ZeldaSpriteSheet.Heart, "Sprites/Items/heart", 1, 2),
                (ZeldaSpriteSheet.Rupee, "Sprites/Items/rupee", 1, 2),
                (ZeldaSpriteSheet.Arrow, "Sprites/Items/arrow", 1, 1),
                (ZeldaSpriteSheet.Bomb, "Sprites/Items/bomb", 2, 2),
                (ZeldaSpriteSheet.Fairy, "Sprites/Items/fairy", 1, 2),
                (ZeldaSpriteSheet.Clock, "Sprites/Items/clock", 1, 1),
                (ZeldaSpriteSheet.WoodenSword, "Sprites/Items/woodensword", 1, 4),
                (ZeldaSpriteSheet.WoodenSwordDU, "Sprites/Projectiles/woodenswordUD", 2, 1),
                (ZeldaSpriteSheet.WoodenSwordRL, "Sprites/Projectiles/woodenswordLR", 2, 1),
                (ZeldaSpriteSheet.WoodenArrow, "Sprites/Items/greenarrow", 4, 1),
                (ZeldaSpriteSheet.ArrowDU, "Sprites/Projectiles/arrowUD", 2, 1),
                (ZeldaSpriteSheet.ArrowRL, "Sprites/Projectiles/arrowLR", 2, 1),
                (ZeldaSpriteSheet.MagicArrow, "Sprites/Items/bluearrow", 4, 1),
                (ZeldaSpriteSheet.MagicArrowDU, "Sprites/Projectiles/bluearrowUD", 2, 1),
                (ZeldaSpriteSheet.MagicArrowRL, "Sprites/Projectiles/bluearrowLR", 2, 1),
                (ZeldaSpriteSheet.MagicBoomerang, "Sprites/Items/magicboomerang", 3, 3),
                (ZeldaSpriteSheet.SwordBeam, "Sprites/Projectiles/swordbeam", 4, 3),
                (
                    ZeldaSpriteSheet.SwordBeamExplosion,
                    "Sprites/Projectiles/swordbeamexplosion",
                    4,
                    3
                ),
                (ZeldaSpriteSheet.DeathSparkle, "Sprites/Projectiles/deathsparkle", 1, 4),
                (ZeldaSpriteSheet.Clink, "Sprites/Projectiles/clink", 1, 1),
                (ZeldaSpriteSheet.BombSmoke, "Sprites/Projectiles/bombexplosion", 1, 3),
                (ZeldaSpriteSheet.Fireball, "Sprites/Projectiles/fireball", 1, 4),
                (ZeldaSpriteSheet.RoomBorder, "Sprites/Environment/roomborder", 1, 1),
                (ZeldaSpriteSheet.NorthDoor, "Sprites/Environment/updoor", 2, 5),
                (ZeldaSpriteSheet.WestDoor, "Sprites/Environment/leftdoor", 1, 10),
                (ZeldaSpriteSheet.EastDoor, "Sprites/Environment/rightdoor", 1, 10),
                (ZeldaSpriteSheet.SouthDoor, "Sprites/Environment/downdoor", 2, 5),
                (ZeldaSpriteSheet.OldManText, "Sprites/Environment/oldmantext", 33, 1),
                (ZeldaSpriteSheet.GameOverText, "Sprites/Menu/GameOver", 1, 1),
                (ZeldaSpriteSheet.GameWinText, "Sprites/Menu/GameWin", 1, 1),
                (ZeldaSpriteSheet.TopDisplay, "Sprites/Menu/top", 1, 1),
                (ZeldaSpriteSheet.LevelOneMap, "Sprites/Menu/mapOne", 1, 1),
                (ZeldaSpriteSheet.EmptyRoom, "Sprites/Environment/emptyroom", 1, 1),
                (ZeldaSpriteSheet.NoMap, "Sprites/Menu/debugMap", 1, 1),
                (ZeldaSpriteSheet.FullHeart, "Sprites/Menu/fullheart", 1, 1),
                (ZeldaSpriteSheet.HalfHeart, "Sprites/Menu/halfheart", 1, 1),
                (ZeldaSpriteSheet.EmptyHeart, "Sprites/Menu/emptyheart", 1, 1),
                (ZeldaSpriteSheet.NoHeart, "Sprites/Menu/noheart", 1, 1),
                (ZeldaSpriteSheet.XCount, "Sprites/Menu/xcount", 1, 1),
                (ZeldaSpriteSheet.ZeroCount, "Sprites/Menu/zero", 1, 1),
                (ZeldaSpriteSheet.OneCount, "Sprites/Menu/one", 1, 1),
                (ZeldaSpriteSheet.TwoCount, "Sprites/Menu/two", 1, 1),
                (ZeldaSpriteSheet.ThreeCount, "Sprites/Menu/three", 1, 1),
                (ZeldaSpriteSheet.FourCount, "Sprites/Menu/four", 1, 1),
                (ZeldaSpriteSheet.FiveCount, "Sprites/Menu/five", 1, 1),
                (ZeldaSpriteSheet.SixCount, "Sprites/Menu/six", 1, 1),
                (ZeldaSpriteSheet.SevenCount, "Sprites/Menu/seven", 1, 1),
                (ZeldaSpriteSheet.EightCount, "Sprites/Menu/eight", 1, 1),
                (ZeldaSpriteSheet.NineCount, "Sprites/Menu/nine", 1, 1),
                (ZeldaSpriteSheet.ActiveWoodenSword, "Sprites/Menu/mapwoodsword", 1, 1),
                (ZeldaSpriteSheet.ActiveWoodenBoomerang, "Sprites/Menu/mapwoodboomerang", 1, 1),
                (ZeldaSpriteSheet.ActiveMagicBoomerang, "Sprites/Menu/activemagicboomerang", 1, 1),
                (ZeldaSpriteSheet.ActiveWoodenArrow, "Sprites/Menu/mapwoodarrow", 1, 1),
                (ZeldaSpriteSheet.ActiveMagicArrow, "Sprites/Menu/activemagicarrow", 1, 1),
                (ZeldaSpriteSheet.ActiveBomb, "Sprites/Menu/mapbomb", 1, 1),
                (ZeldaSpriteSheet.ActiveCandle, "Sprites/Menu/activecandle", 1, 1),
                (ZeldaSpriteSheet.ActiveNoItem, "Sprites/Menu/noactiveitem", 1, 1),
                (ZeldaSpriteSheet.HighlightNoMap, "Sprites/Menu/roomhighlightnomap", 1, 2),
                (ZeldaSpriteSheet.HighlightWithMap, "Sprites/Menu/roomhighlightmap", 1, 2),
                (ZeldaSpriteSheet.PortalGun, "Sprites/Items/portalgun", 4, 1),
                (ZeldaSpriteSheet.ActivePortalGun, "Sprites/Menu/portalgunmenu", 1, 1),
                (ZeldaSpriteSheet.OrangeProjectile, "Sprites/Projectiles/orangeprojectile", 1, 1),
                (ZeldaSpriteSheet.BlueProjectile, "Sprites/Projectiles/blueprojectile", 1, 1),
				(ZeldaSpriteSheet.OrangePortal, "Sprites/Environment/OrangePortal", 1, 1),
				(ZeldaSpriteSheet.BluePortal, "Sprites/Environment/BluePortal", 1, 1),
				(ZeldaSpriteSheet.PauseScreen, "Sprites/Menu/BigPauseScreen", 1, 1),
                (ZeldaSpriteSheet.PauseMapPieces, "Sprites/Menu/PauseMapPieces", 4, 4),
                (ZeldaSpriteSheet.ItemSelect, "Sprites/Menu/ItemSelect", 2, 1),
                (ZeldaSpriteSheet.RetirementText, "Sprites/Environment/retiretext", 32, 1),
                (ZeldaSpriteSheet.Sus, "Sprites/Enemies/sussprites", 4,6),
                (ZeldaSpriteSheet.Candle, "Sprites/Items/candle", 1, 1),
                (ZeldaSpriteSheet.SusSmoke, "Sprites/Projectiles/sussmoke", 1,3),
            };
    };
}
